### ISSUE TITLE
Fails when package defines type as module

### ISSUE THREAD

**Issue by KieranP** [sveltech/svelte-filerouter#415]
Does not properly support type module.

package.json:

```
{
  ...
  "type": "module",
  ...
}
```

routify.config.js

```
export default {
  debug: true,
  pages: 'app/frontend/pages',
  routifyDir: 'app/frontend/.routify'
}
```

Error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kieran/Work/FullApp/routify.config.js from /Users/kieran/Work/FullApp/node_modules/configent/configent.js not supported.
17:16:41 routify.1  | Instead change the require of routify.config.js in /Users/kieran/Work/FullApp/node_modules/configent/configent.js to a dynamic import() which is available in all CommonJS modules.
17:16:41 routify.1  |     at getUserConfig (/Users/kieran/Work/FullApp/node_modules/configent/configent.js:94:35)
17:16:41 routify.1  |     at buildConfig (/Users/kieran/Work/FullApp/node_modules/configent/configent.js:66:33)
17:16:41 routify.1  |     at configent (/Users/kieran/Work/FullApp/node_modules/configent/configent.js:56:12)
17:16:41 routify.1  |     at module.exports (/Users/kieran/Work/FullApp/node_modules/@roxi/routify/lib/utils/config.js:7:40)
17:16:41 routify.1  |     at Object.<anonymous> (/Users/kieran/Work/FullApp/node_modules/@roxi/routify/plugins/cli.js:5:48)
```

**Comment by jakobrosenberg** [comment]
Does renaming the file to `routify.config.cjs` work? Alternatively you can also set the config in package.json

What version of Routify are you using?

**Comment by KieranP** [comment]
@jakobrosenberg Using routify 2.18.4. Using cjs extension means the file gets ignored completely. Note the following. I define pages at "app/frontend/pages", but it tries to access "src/pages".

routify.config.cjs:

```
module.exports = {
  debug: true,
  pages: "app/frontend/pages",
  routifyDir: "app/frontend/.routify"
}
```

```
% yarn routify
yarn run v1.22.11
$ /Users/kieran/Work/FullApp/node_modules/.bin/routify
[Routify] ✖ Pages folder does not exist: src/pages
✨  Done in 0.73s.
```

Yes, I used the config in package.json for now, but in the long term, I'd prefer to keep configuration in its own file.

**Comment by ghostdevv** [comment]
@jakobrosenberg you can just release a patch release to configent to use `await import` which will work regardless of what configent is written in

**Comment by wuliupo** [comment]
+1

when i update to 3.0.0-next, the hmr module was removed.

**Comment by KieranP** [comment]
Over a year later and still experiencing this issue.

package.json has `type: "module"`

If routify.config.js is in ES6 format, I get:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kieran/Work/FullApp/routify.config.js from /Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js not supported.
Instead change the require of routify.config.js in /Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js to a dynamic import() which is available in all CommonJS modules.
    at getUserConfig (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:94:35)
    at buildConfig (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:66:33)
    at configent (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:56:12)
    at module.exports (/Users/kieran/Work/FullApp/node_modules/.pnpm/@roxi+routify@2.18.11/node_modules/@roxi/routify/lib/utils/config.js:7:40)
    at Object.<anonymous> (/Users/kieran/Work/FullApp/node_modules/.pnpm/@roxi+routify@2.18.11/node_modules/@roxi/routify/plugins/cli.js:5:48) {
  code: 'ERR_REQUIRE_ESM'
}
```

If routify.config.js is in CommonJS format, I get:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kieran/Work/FullApp/routify.config.js from /Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js not supported.
routify.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename routify.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/kieran/Work/FullApp/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at getUserConfig (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:94:35)
    at buildConfig (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:66:33)
    at configent (/Users/kieran/Work/FullApp/node_modules/.pnpm/configent@2.2.0/node_modules/configent/configent.js:56:12)
    at module.exports (/Users/kieran/Work/FullApp/node_modules/.pnpm/@roxi+routify@2.18.11/node_modules/@roxi/routify/lib/utils/config.js:7:40)
    at Object.<anonymous> (/Users/kieran/Work/FullApp/node_modules/.pnpm/@roxi+routify@2.18.11/node_modules/@roxi/routify/plugins/cli.js:5:48) {
  code: 'ERR_REQUIRE_ESM'
}
```

If routify.config.js is in CommonJS format, and renamed to routify.config.cjs, I get the following because the config fiule is not found by Routify.

```
[Routify] ✖ Pages folder does not exist: src/pages
```

**Comment by elialbert** [comment]
yes I just experienced this too. was able to slap the whole routify config into package.json.
