### ISSUE TITLE
Navigation error when removing parent module

### ISSUE THREAD

**Issue by jmailaender** [sveltech/svelte-filerouter#473]
Hi there,

I created a new application from the starter repository using `npx @roxi/routify@next create myapp`, added `_module.svelte` with a simple layout plus two child pages `child1` and `child2`. Navigating to the children works fine as long as the parent module is not removed using `<!-- routify:meta reset -->` which raises the error 

```
Uncaught (in promise) Error: couldn't find context for _default_child1_index_md
at handlePageChange (ComposeFragments.svelte? [sm]:44:27)
at $$self.$$.update (ComposeFragments.svelte? [sm]:56:34)
at update (index.mjs:1089:12)
at flush (index.mjs:1060:13)
```

immediatly after changing the URL to `/child1`. Reloading the page displays it correctly, but navigating to `/` fails with a similar error.

The sample application is available [here](https://github.com/dmailaender/routify3-nav-issue).

Is this supposed to work or did I miss anything?

Thanks for your support!
David

**package.json**
```
{
    "name": "starter",
    "type": "module",
    "scripts": {
        "build": "vite build",
        "preview": "vite preview",
        "dev": "vite"
    },
    "devDependencies": {
        "@roxi/routify": "^3.0.0-next.106",
        "@sveltejs/vite-plugin-svelte": "^1.0.0-next.49",
        "mdsvex": "^0.9.3",
        "svelte": "^3.39.0",
        "vite": "^3.0.5"
    }
}
```

**version**
routify: 3.0.0-next.106

**Comment by jakobrosenberg** [comment]
Thanks for the heads up  @dmailaender. I think this is a regression bug. I spotted something similar recently. I'll try get a fix out.
